### ISSUE TITLE
code data fields be removed

### ISSUE THREAD

**Issue by Lpmvb** [syntax-tree/hast-util-raw#13]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Link to runnable example

https://node-rqtpry.stackblitz.io

### Steps to reproduce

![image](https://user-images.githubusercontent.com/34727913/131992702-15ddbada-7160-47fd-9313-2190e882a3c2.png)

### Expected behavior

Do not remove this field.

### Actual behavior

data field be removed.

### Runtime

Node v16

### Package manager

npm v7

### OS

macOS

**Comment by wooorm** [comment]
It is intended that the tree is changed and unrelated data lost, per the readme.
You can handle data fields in a plugin beforehand. Please open a discussion if you have questions about that.

**Comment by JounQin** [comment]
From #29

> It is intended that the tree is changed and unrelated data lost, per the readme.

But in README

> This package is a utility to parse a document again. It passes each node and embedded raw HTML through an HTML parser ([parse5](https://github.com/inikulin/parse5)), to recreate a tree exactly as how a browser would parse it, while keeping the original data and positional info intact.

@wooorm I don't see any mentions of "unrelated data lost" , does anything changed?

I raised a new discussion at https://github.com/orgs/syntax-tree/discussions/148.

**Comment by wooorm** [comment]
The key is in all the other docs: parsing things again.
Everything (except positional info) is lost.

**Comment by wooorm** [comment]
If the words “original data” threw you off, we can discuss changing them

**Comment by JounQin** [comment]
> If the words “original data” threw you off, we can discuss changing them

Can we discuss at https://github.com/orgs/syntax-tree/discussions/148?

> You can handle data fields in a plugin beforehand.

And what about the afterhand? Non `raw` nodes are also affected.

**Comment by remcohaszing** [comment]
Is the issue technical or do we really not want this? Because I think this could be supported in a similar way as the `passThrough` option.

**Comment by wooorm** [comment]
Intentional that a new tree is created; what’s your use case?
Some nodes are also lost due to various reasons

**Comment by remcohaszing** [comment]
I don’t have a need personally. I went down this rabbit hole because of https://github.com/rehypejs/rehype/pull/205. Apparently there’s a need for this, so people are using workarounds.

I understand that re-parsing the tree may cause some data loss. I’m guessing invalid HTML constructs are lost. I don’t understand why we should support positional info and the `passThrough` option, but not `node.data`.

I can imagine it’s useful to have a processor that can highlight markdown code blocks and `raw` nodes, and also support metadata on the markdown code blocks:

````markdown
```js filename="file.js"
console.log('Markdown code block')
```

<pre><code className="language-javascript">console.log('HTML code block')</code></pre>
````

Now a plugin needs to run before `remark-rehype` to support the markdown code block meta, and after to support the initial raw node.

**Comment by wooorm** [comment]
> Apparently there’s a need for this, so people are using workarounds.

People using workarounds not always implies there’s a need 😅

> I don’t understand why we should support positional info and the `passThrough` option, but not `node.data`.

More use cases for them. Positional info on nodes is essentially the entire linting/error reporting capabilities of unified, b) `passThrough` is for MDX to work

> I can imagine it’s useful to have a processor that can highlight markdown code blocks and raw nodes, and also support metadata on the markdown code blocks [...] Now a plugin needs to run before remark-rehype to support the markdown code block meta

That sounds like a remark plugin, which sets `node.data.h*` properties, **before** rehype?

> and after to support the initial raw node.

That sounds like a rehype plugin, which takes `node.properties`?
