### ISSUE TITLE
Nesting of list items when there is an html element in one of them

### ISSUE THREAD

**Issue by mathieudutour** [syntax-tree/hast-util-raw#14]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

6.1.0

### Link to runnable example

https://codesandbox.io/s/remark-rehype-debug-forked-4hivb?file=/src/index.js

### Steps to reproduce

Given the following markdown string:
```
- a <table> b
- c
```
rehype produce the following AST (with the `allowDangerousHtml` option) (position information stripped for clarity):
```
{
  "type": "root",
  "children": [
    {
      "type": "element",
      "tagName": "ul",
      "properties": {},
      "children": [
        {
          "type": "text",
          "value": "\n"
        },
        {
          "type": "element",
          "tagName": "li",
          "properties": {},
          "children": [
            {
              "type": "text",
              "value": "a "
            },
            {
              "type": "raw",
              "value": "<table>"
            },
            {
              "type": "text",
              "value": " b"
            }
          ]
        },
        {
          "type": "text",
          "value": "\n"
        },
        {
          "type": "element",
          "tagName": "li",
          "properties": {},
          "children": [
            {
              "type": "text",
              "value": "c"
            }
          ]
        },
        {
          "type": "text",
          "value": "\n"
        }
      ]
    }
  ]
} 
```
Running rehype-raw on it gives the following AST:
```
{
  "type": "root",
  "children": [
    {
      "type": "element",
      "tagName": "ul",
      "properties": {},
      "children": [
        {
          "type": "text",
          "value": "\n"
        },
        {
          "type": "element",
          "tagName": "li",
          "properties": {},
          "children": [
            {
              "type": "text",
              "value": "a  b\n"
            },
            {
              "type": "element",
              "tagName": "li",
              "properties": {},
              "children": [
                {
                  "type": "text",
                  "value": "c"
                }
              ]
            },
            {
              "type": "text",
              "value": "\n"
            },
            {
              "type": "element",
              "tagName": "table",
              "properties": {},
              "children": []
            }
          ]
        }
      ]
    }
  ]
} 
```

As you can see, the second list item is nested under the first one

### Expected behavior

I would expect the list items to all be at the same level

### Actual behavior

List items level are modified

### Runtime

Node v16

### Package manager

npm v7

### OS

macOS

**Comment by wooorm** [comment]
I believe this behavior is expected because HTML (browsers) do the same for such input:

```html
<ul>
<li>a <table> b</li>
<li>c</li>
</ul>
```

https://astexplorer.net/#/gist/74f889d718e49de2fd8bb6db9aed60cc/d52ee3598c1e6d0cbb2fb54a7c48b59b3e6a1b71
