### ISSUE TITLE
Issues with HTML entities parsing

### ISSUE THREAD

**Issue by danielepolencic** [syntax-tree/hast-util-raw#15]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

test with 7.2.0 and 6.0.2

### Steps to reproduce

```js
import { raw } from "hast-util-raw"

const root = raw({
  type: 'root',
  children: [
    {
      type: 'element',
      tagName: 'span',
      children: [
        {
          type: 'raw',
          value: '/api/v1/&lt;resource-type-name&gt;/&lt;resource-name&gt;', <-- this
        },
      ],
    },
  ],
})

console.log(root)

// {
//   "type": "root",
//   "children": [
//     {
//       "type": "element",
//       "tagName": "span",
//       "properties": {},
//       "children": [
//         {
//           "type": "text",
//           "value": "/api/v1/<resource-type-name>/<resource-name" <-- this
//         }
//       ]
//     }
//   ],
//   "data": {
//     "quirksMode": false
//   }
// }
```

### Expected behavior

The last `>` is retained.

### Actual behavior

The last `>` is removed.

### Runtime

Node v14

### Package manager

npm v7

### OS

macOS

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by wooorm** [comment]
Thanks for the repro, that helped. Complex to track down but it’s solved!
