### ISSUE TITLE
word in a raw node value getting duplicated

### ISSUE THREAD

**Issue by MoLow** [syntax-tree/hast-util-raw#16]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

hast-util-raw 7.2.1

### Link to runnable example

https://stackblitz.com/edit/node-h5dh1f?file=index.js

### Steps to reproduce

this was discovered in node.js docs, see https://github.com/nodejs/node/issues/43864
provided a minimal repro in stackblitz where the last word in this case is repeated

### Expected behavior

the output of
```js
import { raw } from 'hast-util-raw';

const children = [
  { type: 'raw', value: 'this is a thing' },
  { type: 'raw', value: '<sup>' },
  { type: 'text', value: 'b' },
  { type: 'raw', value: '</sup>' },
];

console.log(raw({ type: 'root', children }));
```

should be

```js
{
  type: 'root',
  children: [
    { type: 'text', value: 'this is a thing' },
    {
      type: 'element',
      tagName: 'sup',
      properties: {},
      children: [Array]
    }
  ],
  data: { quirksMode: false }
}
```

### Actual behavior

the word thing is duplicated (changing to another word will result with the same issue):
```js
{
  type: 'root',
  children: [
    { type: 'text', value: 'this is a thingthing' },
    {
      type: 'element',
      tagName: 'sup',
      properties: {},
      children: [Array]
    }
  ],
  data: { quirksMode: false }
}
```

### Affected runtime and version

node18, node 16

### Affected package manager and version

npm@8.11.0

### Affected OS and version

any

**Comment by wooorm** [comment]
Thanks, found it!

**Comment by wooorm** [comment]
[Released](https://github.com/syntax-tree/hast-util-raw/releases/tag/7.2.2)!

**Comment by MoLow** [comment]
Thanks!
