### ISSUE TITLE
RAWTEXT/RCDATA elements are closed inconsistently

### ISSUE THREAD

**Issue by 12Me21** [syntax-tree/hast-util-raw#19]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.2.3

### Steps to reproduce

```js
import {raw} from 'hast-util-raw'
import {u} from 'unist-builder'

let test1 = u('root', [
	u('raw', '<xmp><b>bold</b>after</xmp>'),
])

let test2 = u('root', [
	u('raw', '<xmp>'),
	u('raw', '<b>'),
	u('text', 'bold'),
	u('raw', '</b>'),
	u('text', 'after'),
	u('raw', '</xmp>'),
])

console.log(raw(test1))
console.log(raw(test2))
```

### Expected behavior

The output tree should contain:
- root
   - element: `xmp`
      - text: "&lt;b>bold&lt;/b>after"

(note: &lt;xmp> is parsed in RAWTEXT mode, so tags/escapes aren't parsed inside it, and it only ends when the parser reaches `</xmp>`)

### Actual behavior

- root
   - element: `xmp`
      - text: "&lt;b>bold"
   - text: "after"

the &lt;xmp> element is being closed by the &lt;/b> tag
This affects all elements whose contents are parsed as RAWTEXT/SCRIPT_DATA (&lt;style>, &lt;iframe>, &lt;noembed>, &lt;noframes>, &lt;script>) or RCDATA (&lt;title>, &lt;textarea>)

This can be seen in remark/rehype (with allowDangerousHtml enabled), in cases like:
```
<xmp><b>one</b><b>two</b></xmp>
```
which renders as:
> &lt;b>one<b>two</b>

### Affected runtime and version

node@18.0.0

### Affected package manager and version

npm@8.6.0

### Affected OS and version

Debian 

### Build and bundle tools

Rollup

**Comment by wooorm** [comment]
So, ehh, why are you using obsolete elements anyway? It’s marked as “Non-conforming features” by the HTML spec: so humans shouldn’t use it. Of course, you’re right that it would be good to fix.
A more logical reduced test case can probably be made with `style`, `iframe`, which also use rawtext (note that `xmp` does not relate to rcdata as far as I am aware, that’s for `textarea`, `title`).

**Comment by 12Me21** [comment]
welll, &lt;xmp> is still pretty convenient despite being obsolete, since it's the only "normal" element which is parsed in rawtext mode
anyway, I mentioned rcdata since I believe this bug applies to those elements as well

**Comment by 12Me21** [comment]
it seems like this happens because the text node handler calls `resetTokenizer()`, which always resets the tokenizer into the DATA state, even when inside an element that should be parsed in some other state.
I suppose it would be possible to fix by just not resetting the state? (or only resetting it if it's not DATA/RAWTEXT/RCDATA/SCRIPT_DATA/etc.)

**Comment by wooorm** [comment]
So to repeat: you **really should not use** `xmp`. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/xmp.

---

If you start working on a PR, I recommend basing it off of https://github.com/syntax-tree/hast-util-raw/pull/17. `parse5` changed a lot last major, so this project was rewritten for that. I plan on releasing it in one or two months.
