### ISSUE TITLE
Unable format element's with properties `type` and `value` that aren't tagName: input

### ISSUE THREAD

**Issue by matthewp** [syntax-tree/hast-util-raw#22]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

hast-util-raw@9

### Link to runnable example

https://codepen.io/matthewp/pen/rNRmLLq?editors=1010

### Steps to reproduce

This is enough to cause it

```js
import {raw} from 'hast-util-raw'
import {h} from 'hastscript'

const tree = h('div', {'type':'number','value':'1'}, []);

const reformatted = raw(tree);

console.log(reformatted);
```

Note that if you replace `div` with `input` it works fine. I traced this back from an Astro bug which is reproducible at a higher level here: https://stackblitz.com/edit/github-qdnomy?file=src%2Fpages%2Findex.md . In that example the div comes into hast-util-raw as a "raw" node (I think), but I assume that it's the same underlying issue as in the reduced example.

### Expected behavior

Should be reformatted with the properties as properties.

### Actual behavior

Throws with:  Cannot compile `number` node

### Affected runtime and version

node@18 and Chrome

### Build and bundle tools

Astro

**Comment by ChristianMurphy** [comment]
Hey @matthewp! 👋 
Sorry you ran into a spot of trouble.
It sounds a lot like you are running into https://github.com/syntax-tree/hastscript/issues/21 please see the discussion there

**Comment by matthewp** [comment]
It does seem that way, @ChristianMurphy, is it better to close this one in that case?

**Comment by ChristianMurphy** [comment]
It is better to close this.

> Throws with: Cannot compile number node

`number` is not an MDAST node type https://github.com/syntax-tree/mdast#readme
Handling invalid HTML is not an expectation/requirement of the formatter.

Generate valid HTML for the formatter to work.

---

Where you are generating the AST make sure it is valid.
If you are using `hastscript` this is exactly https://github.com/syntax-tree/hastscript/issues/21
If something else is generating the AST, that could be discussed further there.
