### ISSUE TITLE
Preserve tag name cases

### ISSUE THREAD

**Issue by quadratz** [syntax-tree/hast-util-raw#25]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Add an option to preserve the case of HTML tags. This is similar to issue https://github.com/syntax-tree/hast-util-raw/issues/18, but for HTML tags in general.

Currently, this
```json
{
      "type": "raw",
      "value": "<TabGroup><Tab lang='js' title='JavaScript' /></TabGroup>",     
}
```

will yield
```json
 {
      "type": "element",
      "tagName": "tabgroup",
      // ...
 }
```

### Solution

`TabGroup` and `Tab` should be cased.
It should produce this output instead
```json
 {
      "type": "element",
      "tagName": "TabGroup",
      // ...
 }
```

**Comment by ChristianMurphy** [comment]
Welcome @quadratz! 👋 
HTML is case insensitive, there are no plans to add non-html features to the HTML parser.
It looks like you may be working with XML or JSX.
If you are working with XML consider using https://github.com/syntax-tree/xast-util-from-xml
If you are working with JSX+Markdown consider using https://mdxjs.com/

**Comment by quadratz** [comment]
I think https://mdxjs.com/ is more suitable for my case. Thank you for the help.
