### ISSUE TITLE
Raw nodes parsed as text

### ISSUE THREAD

**Issue by arobase-che** [syntax-tree/hast-util-raw#7]
Hi,

I've encountered some issues using [remark-iframe][remark-iframe]. 
It seems that it is a bug from hast-util-raw.

I just created [a PR][bug] to highlight the problem. A fix will follow soon.

See you soon :D 

Edit: [Fixed ?][fix]

Edit2: Oh ! And @vhf, he helped me a lot to find out the problem. Just to keep him in the loop.

[remark-iframe]: https://github.com/zestedesavoir/zmarkdown/issues/232 "Issue 232"
[bug]: https://github.com/syntax-tree/hast-util-raw/pull/6
[fix]: https://github.com/syntax-tree/hast-util-raw/pull/8

**Comment by arobase-che** [comment]
Hi,

It's me, ... again ^^"

I just merge the two PR and i will close this issues by monday. To no pollute this repo.

💕

**Comment by wooorm** [comment]
I was working on updating to the new version of parse5 and that was harder than expected. Sorry for the delay.

Thanks for all the work @arobase-che! 💪
